export const CREATE_QUIZ = "CREATE_QUIZ";

export const GET_QUIZ = "GET_QUIZ";
export const GET_QUIZ_SUCCEED = "GET_QUIZ_SUCCEED";

export const LIST_QUIZZES = "LIST_QUIZZES";
export const LIST_QUIZZES_SUCCEED = "LIST_QUIZZES_SUCCEED";

export const CREATE_ANSWER = "CREATE_ANSWER";

export const LIST_ANSWERS = "LIST_ANSWERS";
export const LIST_ANSWERS_SUCCEED = "LIST_ANSWERS_SUCCEED";

export const UPDATE_RESULT_QUIZ = "UPDATE_RESULT_QUIZ";

export const GET_CORRECT_ANSWER = "GET_CORRECT_ANSWER";
export const GET_CORRECT_ANSWER_SUCCEED = "GET_CORRECT_ANSWER_SUCCEED";

export const UPDATE_VOTE_ANSWER = "UPDATE_VOTE_ANSWER";